name: Cypress Test

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress node command
        default: node runner.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.0.0

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.input.cli }}
